"use client";
import { FormEvent, useState } from "react";
import { Activity } from "lucide-react";
import { API_BASE, setToken } from "@/services/api";

export function AuthForm({ onDone }: { onDone: () => void }) {
  const [register, setRegister] = useState(false); const [error, setError] = useState(""); const [loading,setLoading]=useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const form = new FormData(e.currentTarget); try { const r=await fetch(`${API_BASE}/auth/${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password')})}); if(!r.ok) throw new Error((await r.json()).detail??'登录失败'); setToken((await r.json()).access_token); onDone(); } catch(e){setError(e instanceof Error?e.message:'登录失败');} finally{setLoading(false);} }
  return <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-6"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-white p-8 shadow-2xl"><div className="mb-8 flex items-center gap-3"><div className="rounded-xl bg-blue-600 p-3 text-white"><Activity/></div><div><h1 className="text-2xl font-bold">FitMind AI</h1><p className="text-sm text-slate-500">有记忆的私人健身助理</p></div></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm">邮箱<input name="email" type="email" required className="mt-1 w-full rounded-lg border px-3 py-2.5 outline-none focus:border-blue-500"/></label><label className="block text-sm">密码<input name="password" type="password" minLength={8} required className="mt-1 w-full rounded-lg border px-3 py-2.5 outline-none focus:border-blue-500"/></label>{error&&<p className="rounded bg-red-50 p-2 text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-blue-600 py-3 font-medium text-white hover:bg-blue-700 disabled:opacity-50">{loading?'请稍候…':register?'创建账号':'登录'}</button></form><button onClick={()=>setRegister(x=>!x)} className="mt-5 w-full text-sm text-blue-600">{register?'已有账号？登录':'没有账号？立即注册'}</button></div></main>;
}
